# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "builds for testing"
lane :build_for_testing do
    scan(
        device: "iPhone SE",
        clean: true
    )
end
